[workspace]

members = [
  "mesatee_services/kms/sgx_app",
  "mesatee_services/fns/sgx_app",
  "mesatee_services/tdfs/sgx_app",
  "mesatee_services/tms/sgx_app",
  "mesatee_services/acs/sgx_app",
  "tests/functional_test/sgx_app",
]

exclude = [
  "mesatee_core",
  "mesatee_config"
]

[patch.crates-io]
# mesatee_core
mesatee_core = { path = "./mesatee_core" }
mesatee_config = { path = "./mesatee_config" }
mesatee_binder = { path = "./mesatee_binder" }

# We cannot remove these crates, because proto crates depend on them
sgx_cov = { git = "https://github.com/baidu/rust-sgx-sdk", rev = "v1.0.9" }
sgx_urts = { git = "https://github.com/baidu/rust-sgx-sdk", rev = "v1.0.9" }
sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk", rev = "v1.0.9" }
